name: Sync from Public

on:
  workflow_dispatch:
    inputs:
      public_branch:
        description: Name of branch in PUBLIC repo to sync from
        type: string
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-from-public:
    uses: SETT-Centre-Data-and-AI/workflows/.github/workflows/sync-from-public.yaml@release
    with:
      public_branch: ${{ github.event.inputs.public_branch }}
      private-repo: your-org/your-private-repo
      private-repo-main-branch: main
      private-repo-incoming-branch: incoming_from_public
      public-repo: your-org/your-public-repo
    secrets: inherit
