name: Build and Test

# ======================================================================= #
# Build and Test
# builds and tests in PRIVATE repo when PR opened to main branch
# ======================================================================= #

on:
  workflow_call: {}

jobs:
  env-config:
    uses: ./.github/workflows/config.yaml

  build-and-smoke-test:
    needs: env-config
    if: >
      github.repository == needs.env-config.outputs.PRIVATE_REPO

    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          python-version: ${{ needs.env-config.outputs.BUILD_SMOKE_PYTHON_VERSION }}

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    env:
      PACKAGE_NAME: ${{ needs.env-config.outputs.PACKAGE_NAME }}
      PRIVATE_REPO: ${{ needs.env-config.outputs.PRIVATE_REPO }}
      PRIVATE_REPO_MAIN_BRANCH: ${{ needs.env-config.outputs.PRIVATE_REPO_MAIN_BRANCH }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v5

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install UV, Poetry, and tooling
      run: |
        python -m pip install --upgrade pip
        pip install uv poetry build pytest

    - name: Build Package
      run: |
        rm -rf dist
        python -m build

    - name: Install Package (Poetry)
      run: |
        poetry install
        poetry run python -c "import $PACKAGE_NAME"

    - name: Install Package (UV)
      run: |
        uv venv .venv-uv
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          source .venv-uv/Scripts/activate
        else
          source .venv-uv/bin/activate
        fi

        uv pip install dist/*.whl
        python -c "import $PACKAGE_NAME"

  run-tests:
    needs: env-config
    if: >
      github.repository == needs.env-config.outputs.PRIVATE_REPO

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.env-config.outputs.TEST_MATRIX_JSON) }}

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    env:
      PACKAGE_NAME: ${{ needs.env-config.outputs.PACKAGE_NAME }}
      PRIVATE_REPO: ${{ needs.env-config.outputs.PRIVATE_REPO }}
      PRIVATE_REPO_MAIN_BRANCH: ${{ needs.env-config.outputs.PRIVATE_REPO_MAIN_BRANCH }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v5

    - name: Install System Dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install UV and Tooling
      run: |
        python -m pip install --upgrade pip
        pip install uv build pytest

    - name: Install Package (UV)
      run: |
        uv sync

    - name: Run Tests
      run: |
        uv run --active pytest
